import { Header } from '@/components/header'
import './globals.css'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { Footer } from '@/components/footer'

const jakarta = Plus_Jakarta_Sans({
  weight: ['300', '400', '500', '600', '800'],
  subsets: ['latin'] ,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
